### PR TITLE
Extra Data Flag fix + Support for GameID

### PR DESCRIPTION
**Pull request by BinaryAlien**
+ Added support for the GameID field in A2S_INFO query responses
~ Fix: Use of the Extra Data Flag (EDF) in order to determine what extra fields to read from the A2S_INFO query response

### CODE REVIEW

**Comment by WardPearce** [comment]
Thanks for the PR, I just came back from a trip. I'll check it out later today.

**Review by WardPearce — CHANGES_REQUESTED** [review]
Thanks for the PR, just got some minor changes.

https://github.com/BinaryAlien/aioquery/blob/fix-and-gameid/aioquery/__init__.py#L112

Use `if data_opts.data:`
instead of `if len(data_opts.data) != 0`, functionality should be the same.

https://github.com/BinaryAlien/aioquery/blob/fix-and-gameid/aioquery/models.py#L116
Any reason the splitting was removed here?

**Comment by BinaryAlien** [comment]
Hello ! Thank you very much for the review ! I put `if data_opts.data:` back, I did not notice it was the same thing on the moment

https://github.com/BinaryAlien/aioquery/blob/fix-and-gameid/aioquery/__init__.py#L126
Splitting was moved here !

https://github.com/WardPearce/aioquery/blob/master/aioquery/models.py#L116
The condition `if "," in data else None` should have been `if "," in data["tags"] else None` and when changing this I thought the splitting could be done directly into the `info` function

**Comment by WardPearce** [comment]
Awesome! I'll pack this now.

**Comment by WardPearce** [comment]
This has now been packed under version `1.1.4`.

**Comment by BinaryAlien** [comment]
Much appreciated !

**Pull request merged**
